# Generated by Django 6.0.3 on 2026-03-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('transactions', '0003_deadlettertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='transactions.transaction'),
        ),
    ]
