# Generated by Django 6.0.3 on 2026-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_dlq',
            field=models.BooleanField(default=False),
        ),
    ]
