# Generated by Django 6.0.3 on 2026-03-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_is_dlq'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
    ]
